services:
  vpn-server:
    build: .
    container_name: vpn-server
    privileged: true
    network_mode: host
    volumes:
      - /lib/modules:/lib/modules:ro
      - ./backend/data:/app/backend/data
    restart: always
    environment:
      - SERVER_ENDPOINT=${SERVER_ENDPOINT}
      - JWT_SECRET=${JWT_SECRET}
    cap_add:
      - NET_ADMIN
      - NET_RAW

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: vpn-dashboard-nginx
    network_mode: host
    restart: always
    depends_on:
      - vpn-server
